org: ecvph
service: python-serverless-rey

provider:
  name: aws
  runtime: python3.12
  role: ${env:AWS_IAM_ROLE}

functions:
  createOneProduct:
    handler: handlers/productHandler.create_one_product
    events:
      - httpApi:
          path: /products
          method: post
  getAllProducts:
    handler: handlers/productHandler.get_all_products_handler
    events:
      - httpApi:
          path: /products
          method: get
  productModification:
    handler: handlers/productHandler.product_modification
    events:
      - httpApi:
          path: /product_modification
          method: get
      - httpApi:
          path: /product_modification
          method: put
      - httpApi:
          path: /product_modification
          method: delete
  batchCreateProducts:
    handler: handlers/productBatchHandler.batch_create_products_handler
    events:
      - s3:
          bucket: products-s3bucket-rey
          event: s3:ObjectCreated:*
          rules:
            - prefix: for_create/
          existing: true
  batchDeleteProducts:
    handler: handlers/productBatchHandler.batch_delete_products_handler
    events:
      - s3:
          bucket: products-s3bucket-rey
          event: s3:ObjectCreated:*
          rules:
            - prefix: for_delete/
          existing: true
